// <auto-generated />
using System;
using MarketNewsApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketNewsApp.Data.Migrations
{
    [DbContext(typeof(MarketNewsDbContext))]
    partial class MarketNewsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("MarketNewsApp.Data.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            PasswordHash = "SET_AT_FIRST_LOGIN",
                            Role = "Administrator",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MarketNewsApp.Data.AgentConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AzureApiVersion")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureDeployment")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AzureEndpoint")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("CopilotModel")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AgentSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AzureApiVersion = "2024-10-21",
                            Provider = "copilot"
                        });
                });

            modelBuilder.Entity("MarketNewsApp.Data.ApplicationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ApplicationSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "IANA timezone for scheduled reports",
                            Key = "timezone",
                            Value = "Europe/Athens"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Runtime configuration refresh interval",
                            Key = "configuration-cache-minutes",
                            Value = "5"
                        });
                });

            modelBuilder.Entity("MarketNewsApp.Data.ConfigurationAuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("ConfigurationAuditEntries");
                });

            modelBuilder.Entity("MarketNewsApp.Data.PipelineCheckpoint", b =>
                {
                    b.Property<string>("RunId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RunDate")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RunId", "Stage", "SourceName");

                    b.HasIndex("RunDate", "Stage");

                    b.ToTable("PipelineCheckpoints");
                });

            modelBuilder.Entity("MarketNewsApp.Data.EmailConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmailSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromDisplayName = "Market News AI",
                            Recipients = "recipient1@example.com,recipient2@example.com",
                            SubjectTemplate = "Market News AI — {{date}}"
                        });
                });

            modelBuilder.Entity("MarketNewsApp.Data.EmailRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("EmailRecipients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "recipient1@example.com",
                            DisplayName = "Primary recipient",
                            IsEnabled = true
                        },
                        new
                        {
                            Id = 2,
                            Address = "recipient2@example.com",
                            DisplayName = "Secondary recipient",
                            IsEnabled = true
                        });
                });

            modelBuilder.Entity("MarketNewsApp.Data.FeatureFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("FeatureFlags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEnabled = true,
                            Key = "scrape-cache"
                        },
                        new
                        {
                            Id = 2,
                            IsEnabled = true,
                            Key = "summary-cache"
                        });
                });

            modelBuilder.Entity("MarketNewsApp.Data.PromptConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Prompts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsEnabled = true,
                            Key = "source-system",
                            Template = "Είσαι επιμελητής που αποδίδει στα ελληνικά ΜΟΝΟ τις πληροφορίες του παρεχόμενου scraped κειμένου. Η ακρίβεια και η πιστότητα στην πηγή είναι σημαντικότερες από την έκταση ή την ερμηνεία. Χρησιμοποιείς HTML formatting με h3, ul/li, strong και table class=market-table. Χρησιμοποιείς αποκλειστικά το περιεχόμενο της συγκεκριμένης πηγής, δεν προσθέτεις γεγονότα ή επενδυτικές συστάσεις, και διατηρείς αριθμούς, ποσοστά, ημερομηνίες και επιφυλάξεις."
                        },
                        new
                        {
                            Id = 2,
                            IsEnabled = true,
                            Key = "source-user",
                            Template = "Σήμερα είναι {{today}}. Παρακάτω δίνεται το περιεχόμενο ΑΠΟΚΛΕΙΣΤΙΚΑ από την πηγή «{{sourceName}}» ({{sourceUrl}}) για την περίοδο {{sinceDate}} – {{today}}. Απόδωσε στα ελληνικά μόνο τα γεγονότα, αριθμούς και ρητές θέσεις. Ξεκίνα με <div class=\"section\"><h2>📄 {{sourceName}}</h2><p class=\"source-tag\">Πηγή: <a href=\"{{sourceUrl}}\">{{sourceName}}</a></p> και κλείσε με </div>. Αν το περιεχόμενο είναι μόνο disclaimer, όροι, cookie/privacy notice ή απαιτεί σύνδεση, επέστρεψε μόνο NO_CONTENT. Γράψε μόνο HTML. ΠΕΡΙΕΧΟΜΕΝΟ ΠΗΓΗΣ: {{content}}"
                        },
                        new
                        {
                            Id = 3,
                            IsEnabled = true,
                            Key = "translation",
                            Template = "Μετέφρασε πιστά στα ελληνικά το παρακάτω scraped περιεχόμενο από την πηγή «{{sourceName}}». Μην το συνοψίσεις, μην προσθέσεις πληροφορίες και μην χρησιμοποιήσεις HTML ή Markdown. Διατήρησε αλλαγές γραμμής, αριθμούς, ονόματα εταιρειών και χρηματοοικονομικούς όρους. ΠΕΡΙΕΧΟΜΕΝΟ: {{content}}"
                        },
                        new
                        {
                            Id = 4,
                            IsEnabled = true,
                            Key = "synthesis",
                            Template = "Με βάση τις αναλύσεις ανά πηγή για {{sinceDate}} – {{today}}, σύνταξε ΣΥΝΘΕΤΙΚΗ ΕΠΙΣΚΟΠΗΣΗ σε HTML στα ΕΛΛΗΝΙΚΑ. Κάλυψε κοινά θέματα, αποκλίσεις, συνολική αξιολόγηση και επενδυτικές συστάσεις που προκύπτουν από τις πηγές. Ξεκίνα με <div class=\"section synthesis\"><h2>🔍 Συνθετική Επισκόπηση Αγορών — {{today}}</h2> και κλείσε με </div>. Μόνο HTML. ΑΝΑΛΥΣΕΙΣ ΑΝΑ ΠΗΓΗ: {{snippets}}"
                        });
                });

            modelBuilder.Entity("MarketNewsApp.Data.ReportConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSourceList")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeTranslatedContent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LookbackDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSummarySourceCharacters")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTranslationSourceCharacters")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ReportSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IncludeSourceList = true,
                            IncludeTranslatedContent = true,
                            LookbackDays = 10,
                            MaxSummarySourceCharacters = 20000,
                            MaxTranslationSourceCharacters = 30000
                        });
                });

            modelBuilder.Entity("MarketNewsApp.Data.ReportTemplateConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ReportTemplates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyTemplate = "{{ai_summary}}",
                            IsDefault = true,
                            IsEnabled = true,
                            Name = "Daily market report",
                            SubjectTemplate = "Market News AI - {{date}}"
                        });
                });

            modelBuilder.Entity("MarketNewsApp.Data.SchedulingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DailySendTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SchedulingSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailySendTime = "07:00",
                            IsEnabled = true
                        });
                });

            modelBuilder.Entity("MarketNewsApp.Data.ScrapeSourceConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcludeSelectorsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpandButtonTextsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExtraSettleMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FollowFirstLinkSelector")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScreenshotSelectorsJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRegion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeoutMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("WaitFor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ScrapeSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExtraSettleMs = 0,
                            IsEnabled = true,
                            Name = "Bloomberg Markets",
                            SelectorsJson = "[\"article\",\"[data-component='headline']\",\"h1\",\"h2\",\"h3\",\".story-package-module__headline\"]",
                            SourceRegion = "International",
                            SortOrder = 1,
                            TimeoutMs = 20000,
                            Url = "https://www.bloomberg.com/markets",
                            WaitFor = "body"
                        },
                        new
                        {
                            Id = 2,
                            ExtraSettleMs = 0,
                            IsEnabled = true,
                            Name = "BlackRock Investment Institute",
                            SelectorsJson = "[\"article\",\".content-block\",\"h1\",\"h2\",\"p\",\".editorial-content\"]",
                            SourceRegion = "International",
                            SortOrder = 2,
                            TimeoutMs = 25000,
                            Url = "https://www.blackrock.com/corporate/insights/blackrock-investment-institute/publications/weekly-commentary",
                            WaitFor = "body"
                        },
                        new
                        {
                            Id = 3,
                            ExtraSettleMs = 0,
                            IsEnabled = true,
                            Name = "T. Rowe Price Global Markets",
                            SelectorsJson = "[\"article\",\"main\",\".article-body\",\"h1\",\"h2\",\"h3\",\"p\"]",
                            SourceRegion = "International",
                            SortOrder = 3,
                            TimeoutMs = 25000,
                            Url = "https://www.troweprice.com/personal-investing/resources/insights/global-markets-weekly-update.html",
                            WaitFor = "main"
                        },
                        new
                        {
                            Id = 4,
                            ExtraSettleMs = 0,
                            IsEnabled = true,
                            Name = "BNP Paribas AM Viewpoint",
                            SelectorsJson = "[\"article\",\"main\",\"p\",\".article-title\",\"h1\",\"h2\",\"h3\",\".card-title\"]",
                            SourceRegion = "International",
                            SortOrder = 4,
                            TimeoutMs = 20000,
                            Url = "https://viewpoint.bnpparibas-am.com/",
                            WaitFor = "body"
                        },
                        new
                        {
                            Id = 5,
                            ExtraSettleMs = 0,
                            IsEnabled = true,
                            Name = "Edward Jones Weekly Update",
                            SelectorsJson = "[\"article\",\"main\",\".article-body\",\"h1\",\"h2\",\"h3\",\"p\"]",
                            SourceRegion = "International",
                            SortOrder = 5,
                            TimeoutMs = 25000,
                            Url = "https://www.edwardjones.com/us-en/market-news-insights/stock-market-news/stock-market-weekly-update",
                            WaitFor = "main"
                        },
                        new
                        {
                            Id = 6,
                            ExcludeSelectorsJson = "[\".jp-seo-modal-container\",\".jpm-am-overlay-disclaimer\"]",
                            ExpandButtonTextsJson = "[\"Read more\"]",
                            ExtraSettleMs = 0,
                            IsEnabled = true,
                            Name = "JPMorgan Weekly Market Recap",
                            SelectorsJson = "[\"article\",\"main\",\".content\",\"h1\",\"h2\",\"h3\",\"p\"]",
                            SourceRegion = "International",
                            SortOrder = 6,
                            TimeoutMs = 25000,
                            Url = "https://am.jpmorgan.com/us/en/asset-management/institutional/insights/market-insights/market-updates/weekly-market-recap/",
                            WaitFor = "body"
                        },
                        new
                        {
                            Id = 7,
                            ExtraSettleMs = 0,
                            FollowFirstLinkSelector = "#articles-list .chip h2 a",
                            IsEnabled = true,
                            Name = "Citi Market Insights",
                            SelectorsJson = "[\"article\",\"main\",\".content-area\",\"h1\",\"h2\",\"h3\",\"p\"]",
                            SourceRegion = "International",
                            SortOrder = 7,
                            TimeoutMs = 25000,
                            Url = "https://marketinsights.citi.com/Market-Commentary/Weekly-Market-Update/index.html",
                            WaitFor = "body"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
